name: Publish Package

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release'
        required: true
        type: string

jobs:
  build:
    permissions:
      contents: write
      issues: write
      packages: write
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup node environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          always-auth: true
          registry-url: https://npm.pkg.github.com/
          scope: '@amtins'

      - name: Check if tag exists
        env:
          AVAILABLE_VERSIONS: npm view @amtins/super-duper-ci versions --json
        if: ${{!contains(fromJSON(env.AVAILABLE_VERSIONS), inputs.tag)}}
        run: exit 1;

      - name: Release tag
        if: success()
        run: |
          echo ${{ github.ref_type }}
          echo ${{ github.ref_name }}
          echo "the current version is: $(npm view @amtins/super-duper-ci version)"
          echo "the next version is: $(npm view @amtins/super-duper-ci dist-tags.next)"
          echo "All versions available: $(npm view @amtins/super-duper-ci versions --json)"
          echo -e "Dist tags:\n$(npm dist-tag ls @amtins/super-duper-ci)"
          npm dist-tag add @amtins/super-duper-ci@${{ inputs.tag }} latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Tag does not exist
        if: failure()
        run: echo "FAIL to deploy tag"

