name: Publish Package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          always-auth: true
          registry-url: https://npm.pkg.github.com/
          scope: '@amtins'
      - run: |
          npm dist-tag ls @amtins/super-duper-ci
          npm dist-tag add @amtins/super-duper-ci@2.5.5 latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.SUPER_DUPER_CI }}
          NODE_AUTH_TOKEN: ${{ secrets.SUPER_DUPER_CI }}
