name: Publish Package

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Tag to release'
        required: false
        type: boolean

jobs:
  build:
    permissions:
      contents: write
      issues: write
      packages: write
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          always-auth: true
          registry-url: https://npm.pkg.github.com/
          scope: '@amtins'
      - run: |
          echo ${{ github.ref_type }}
          echo ${{ github.ref_name }}
          npm dist-tag ls @amtins/super-duper-ci
          npm dist-tag add @amtins/super-duper-ci@${{ env.CLEAN_TAG }} latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          TAGS: ${{ inputs.tags }}
          CLEAN_TAG: $(echo ${{ github.ref_name }} | sed 's/v//')
