name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          always-auth: true
          registry-url: https://npm.pkg.github.com/

      - name: Install dependencies
        env :
          CI: true
        run: |
          npm ci
          npm test

      - name: Release something ? 📦
        if: success()
        run: npm run release:ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.COUSCOUS }}
          NODE_AUTH_TOKEN: ${{ secrets.COUSCOUS }}

      - name: Something failed 🫣
        if: failure()
        run: |
          echo "It seems something didn't go as planned 🤔"
          exit 1