name: Release NPM Package

on:
  release:
    types: [released]

jobs:
  build:
    permissions:
      contents: write
      packages: write

    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          always-auth: true
          registry-url: https://npm.pkg.github.com/
          scope: '@amtins'
      - run: |
          npm dist-tag ls @amtins/super-duper-ci
          npm dist-tag add @amtins/super-duper-ci@$(npm view @amtins/super-duper-ci dist-tags.main) latest
          exit 0
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
