name: Release NPM Package

on:
  release:
    types: [released]

jobs:
  release:

    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          always-auth: true
          registry-url: https://npm.pkg.github.com/
          scope: '@amtins'
      - run: |
          echo ${{ toJson(github) }}
          latest=$(echo ${{github.ref}} | tr -d 'v')
          npm dist-tag add @amtins/super-duper-ci@$(echo $latest) latest
          exit 0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
