name: Release NPM Package

on:
  release:
    types: [released]

jobs:
  release:

    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          always-auth: true
          registry-url: https://npm.pkg.github.com/
          scope: '@amtins'
      - run: |
          echo "GITHUB_PACKAGE_VERSION=$("${{github.ref_name}}" | cut -c 2-)" >> $GITHUB_ENV
          npm dist-tag add @amtins/super-duper-ci@$(echo "${{ env.GITHUB_PACKAGE_VERSION }}") latest
          exit 0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
