name: Release Prerelease

on:
  release:
    types: [published, edited, released]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
      # if: ${{ github.event.release ===}}
        run: echo ${{ toJson(github.event.release) }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          always-auth: true
          registry-url: https://npm.pkg.github.com/
          scope: '@amtins'
      - run: |
          npm dist-tag ls @amtins/super-duper-ci
          npm publish --tag next
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
